# Generated by Django 4.1.6 on 2023-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('face', 'Face'), ('lip', 'Lip'), ('eye', 'Eye')], default='face', max_length=4),
        ),
    ]
