# Generated by Django 4.2.7 on 2023-12-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_useractionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
