# Generated by Django 4.2.7 on 2023-12-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
